#pragma kernel PrefixSum
#pragma enable_d3d11_debug_symbols

RWStructuredBuffer<int> Input;
#define THREADS_PER_GROUP 4

groupshared uint groupPrefixSum[THREADS_PER_GROUP];
groupshared uint invertedBitAtStep[THREADS_PER_GROUP];
uniform int Step; 

int ComputeExclusivePrefixSumForGroup(int threadId, int value)
{
    groupPrefixSum[threadId] = value;
    GroupMemoryBarrierWithGroupSync();

    for (int offset = 1; offset < THREADS_PER_GROUP; offset *= 2)
    {
        bool inBounds = threadId >= offset;
        int childLeftLeafSum = inBounds ? groupPrefixSum[threadId - offset] : 0;
        int childRightLeafSum = groupPrefixSum[threadId];
        
        GroupMemoryBarrierWithGroupSync();
        groupPrefixSum[threadId] = childLeftLeafSum + childRightLeafSum;
    }

    return groupPrefixSum[threadId] - value;
}

int GetGroupPrefixSum(int threadId)
{
    return groupPrefixSum[threadId];
}

[numthreads(THREADS_PER_GROUP,1,1)]
void PrefixSum(uint3 id : SV_DispatchThreadID, uint3 threadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    const int value = Input[id.x];
    const int mask = 1 << Step;
    const int bit = (value & mask) == mask;
    const int invertedBit = 1 - bit;
    invertedBitAtStep[threadId.x] = invertedBit;
    const int prefixSum = ComputeExclusivePrefixSumForGroup(threadId.x, invertedBit);
    
    int lastIndex = THREADS_PER_GROUP - 1;
    int groupPrefixSum = GetGroupPrefixSum(lastIndex) - invertedBitAtStep[lastIndex];

    const int totalFalseBits = groupPrefixSum + invertedBitAtStep[lastIndex];
    const int indexIfBitIsFalse = prefixSum;
    const int indexIfBitIsTrue = threadId.x - indexIfBitIsFalse + totalFalseBits;
    const int localScatterIndex = bit ? indexIfBitIsTrue : indexIfBitIsFalse;
    const int globalScatterIndex = groupId.x * THREADS_PER_GROUP + localScatterIndex;

    Input[globalScatterIndex] = Input[id.x];
}