#pragma kernel PrefixSum
#pragma enable_d3d11_debug_symbols
#include "RadixSort.hlsl"

RWStructuredBuffer<int> Input;
uniform int BitOffset;

[numthreads(THREADS_PER_GROUP,1,1)]
void PrefixSum(uint3 id : SV_DispatchThreadID, uint3 threadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    const int value = Input[id.x];
    const int bit = GetBitAtPosition(value, BitOffset);
    const int invertedBit = 1 - bit;
    const int prefixSum = ComputeExclusivePrefixSumForGroup(threadId.x, invertedBit);
    const int scatterIndex = ComputeScatterIndex(threadId.x, groupId.x, bit, prefixSum);

    Input[scatterIndex] = value;
}
