#pragma kernel RunPlocPlusPlus
#pragma enable_d3d11_debug_symbols
#define THREADS 2
#include "NearestNeighbour.hlsl"

void Merge()
{
}

void Compress()
{
}

[numthreads(THREADS,1,1)]
void RunPlocPlusPlus(const int globalId : SV_DispatchThreadID, const int threadId : SV_GroupThreadID, const int groupId : SV_GroupID)
{
    uint nn = FindNearestNeighbour(threadId, groupId * THREADS, globalId);
    Nodes[globalId].SetLeftChild(nn);
}