#pragma kernel RunPlocPlusPlus
#pragma enable_d3d11_debug_symbols
#define THREADS 4
#include "NearestNeighbour.hlsl"

void Merge()
{
}

void Compress()
{
}

[numthreads(THREADS,1,1)]
void RunPlocPlusPlus(const int globalId : SV_DispatchThreadID, const int threadId : SV_GroupThreadID, const int groupId : SV_GroupID)
{
    if (IsInBounds(globalId))
    {
        Nodes[globalId].__Data.x = FindNearestNeighbour(threadId, groupId * THREADS);
    }
}